export const mobileTheme = {
  '--adm-color-primary': '#1677FF',
  '--adm-color-success': '#52c41a',
  '--adm-color-warning': '#faad14',
  '--adm-color-danger': '#ff3141',
  '--adm-color-text': '#333333',
  '--adm-color-text-secondary': '#666666',
  '--adm-color-weak': '#999999',
  '--adm-color-background': '#ffffff',
  '--adm-color-border': '#eeeeee',
  '--adm-font-size-main': '14px',
  '--adm-font-size-3': '12px',
  '--adm-font-size-7': '16px',
  '--adm-font-size-8': '18px',
  '--adm-radius-s': '4px',
  '--adm-radius-m': '8px',
  '--adm-radius-l': '12px',
  '--adm-button-border-radius': '8px',
  '--adm-nav-bar-height': '44px',
  '--adm-list-item-padding-left': '16px',
};
